test

diff --git a/.github/actions/release/action.yml b/.github/actions/release/action.yml
--- a/.github/actions/release/action.yml
+++ b/.github/actions/release/action.yml
@@ -84,44 +84,43 @@ runs:
         COMPONENT_DIR=""
         PREVIOUS_STABLE_BUNDLE_TAG="${{ steps.get_previous_release_bundle_tag.outputs.previous_stable_bundle_tag }}"
 
-        # Get current stable branch name
-        # If MASTER, use root .version
-        # Else use branch name
-        if [[ "${{ inputs.github_ref_name }}" == "master" ]]; then
-          CURRENT_STABLE_BRANCH_MAJOR_VERSION=$(grep -E "MAJOR" .version | cut -d '=' -f2)
-          RELEASE_CLOUD=1
-        else
-          CURRENT_STABLE_BRANCH_MAJOR_VERSION=$(echo ${{ inputs.github_ref_name }} | cut -d '.' -f1,2)
-          RELEASE_CLOUD=0
-        fi
-        echo "Current stable branch major version: $CURRENT_STABLE_BRANCH_MAJOR_VERSION"
+        # Get current stable branch name and major version
+        # CURRENT_STABLE_BRANCH_MAJOR_VERSION is used to search previous stable tags
+        # CURRENT_STABLE_BRANCH_MAJOR_VERSION comes from component .version file in the latest release bundle tag
+        # Get .version MAJOR var content from ref pointed by the last release bundle tag
+        CURRENT_STABLE_BRANCH_MAJOR_VERSION=$(git show $PREVIOUS_STABLE_BUNDLE_TAG:.version |grep MAJOR | cut -d '=' -f2)
+        echo "Current stable major version: $CURRENT_STABLE_BRANCH_MAJOR_VERSION"
 
         # Get previous and new version tags for components
         for component in ${COMPONENTS_OSS[@]}; do
-          MAJOR_VERSION=$(grep -E "MAJOR" .version | cut -d '=' -f2)
-          MINOR_VERSION=$(grep -E "MINOR" .version.$component | cut -d '=' -f2)
+          #MAJOR_VERSION=$(grep -E "MAJOR" .version | cut -d '=' -f2)
+          #MINOR_VERSION=$(grep -E "MINOR" .version | cut -d '=' -f2)
+          MAJOR_VERSION=$(git show origin/${{ inputs.release_branch }}:.version |grep MAJOR | cut -d '=' -f2)
+          MINOR_VERSION=$(git show origin/${{ inputs.release_branch }}:.version.$component |grep MINOR | cut -d '=' -f2)
           # Previous stable tags array
-          PREVIOUS_STABLE_TAGS+=($(git tag -l --sort=-version:refname "$component-$CURRENT_STABLE_BRANCH_MAJOR_VERSION.*" | grep -E "$component-$CURRENT_STABLE_BRANCH_MAJOR_VERSION.[0-9]+$" | head -n 1))
+          #PREVIOUS_STABLE_TAGS+=($(git tag -l --sort=-version:refname "$component-$CURRENT_STABLE_BRANCH_MAJOR_VERSION.*" | grep -E "$component-$CURRENT_STABLE_BRANCH_MAJOR_VERSION.[0-9]+$" | head -n 1))
+          PREVIOUS_STABLE_COMPONENT_TAGS+=($(git tag --points-at $(git rev-parse "$PREVIOUS_STABLE_BUNDLE_TAG") | grep -E "$component-$CURRENT_STABLE_BRANCH_MAJOR_VERSION.[0-9]+$" | head -n 1))
+
           # New stable tags array
           TMP_STABLE_TAGS+=("$component-$MAJOR_VERSION.$MINOR_VERSION")
         done
 
-        echo "Previous releases were: ${PREVIOUS_STABLE_TAGS[*]}"
+        echo "Previous releases were: ${PREVIOUS_STABLE_COMPONENT_TAGS[*]}"
         echo "Temporary new releases are: ${TMP_STABLE_TAGS[*]}"
 
         # Building final NEW_STABLE_TAGS with the new version tags only
         # Iterate over elements of TMP_STABLE_TAGS
         for new_tag in "${TMP_STABLE_TAGS[@]}"; do
           found=false
-          # Iterate over elements of PREVIOUS_STABLE_TAGS
-          for old_tag in "${PREVIOUS_STABLE_TAGS[@]}"; do
+          # Iterate over elements of PREVIOUS_STABLE_COMPONENT_TAGS
+          for old_tag in "${PREVIOUS_STABLE_COMPONENT_TAGS[@]}"; do
             # Compare elements
             if [ "$new_tag" == "$old_tag" ]; then
               found=true
               break
             fi
           done
-          # If element not found in PREVIOUS_STABLE_TAGS, add it to NEW_STABLE_TAGS
+          # If element not found in PREVIOUS_STABLE_COMPONENT_TAGS, add it to NEW_STABLE_TAGS
           if ! $found; then
             NEW_STABLE_TAGS+=("$new_tag")
           fi
@@ -136,23 +135,28 @@ runs:
         echo "SCOPE_VERSION=$SCOPE_VERSION" >> "$GITHUB_ENV"
       shell: bash
 
-    - name: Add new release tags to stable branch
+    - name: Add new stable tags to release branch
       run: |
         set -eux
 
-        # Add new stable tags to stable branch
+        # Set git local configuration
         echo "Configuring git."
         git config --global user.email "release@centreon.com"
         git config --global user.name "Centreon"
 
-        # Create release tags on git for each release components
+        # Add new stable release bundle tag to release branch
+        echo "::notice::Tagging branch ${{ inputs.release_branch }} with ${{ inputs.release_bundle_tag }}."
+        git tag -a "${{ inputs.release_bundle_tag }}" -m "${{ inputs.release_bundle_tag }}"
+        git push --follow-tags
+        # Add new component release tags on release branch for each release components
         # Abort if no tags or existing tag
         echo "Creating release tags."
         for TAG in ${NEW_STABLE_TAGS[@]}; do
           if [ -z $(git tag --list "$TAG" | head -n 1) ] && [ -n $TAG ]; then
             git tag -a "$TAG" -m "$TAG"
             git push --follow-tags
-            echo "::notice::Tagging stable branch with $TAG."
+            # git status
+            echo "::notice::Tagging branch ${{ inputs.release_branch }} with $TAG."
           else
             echo "::error::Release tag $TAG already exists, exiting."
             exit 1
@@ -185,8 +189,9 @@ runs:
           if [ -n $TAG ]; then
             echo "Creating GITHUB release with title $TAG for tag $TAG."
             gh release create $TAG --target "${{ inputs.github_ref_name }}" --title "$TAG" --verify-tag
+            echo "::notice::Creating github release from $TAG."
           else
-            echo "::error::Release tag $TAG was empty, exiting."
+            echo "::error::Release tag $TAG was empty, could not create github release for $TAG, exiting."
             exit 1
           fi
         done
@@ -194,96 +199,96 @@ runs:
       env:
         GH_TOKEN: ${{ github.token }}
 
-    - name: Create stable JIRA versions from new release tags
-      run: |
-        set -eux
+    # - name: Create stable JIRA versions from new release tags
+    #   run: |
+    #     set -eux
 
-        # Call JIRA to provide new jira versions to create
-        # Webhook url
-        JIRA_INCOMING_WEBHOOK="${{ inputs.jira_webhook_url }}"
+    #     # Call JIRA to provide new jira versions to create
+    #     # Webhook url
+    #     JIRA_INCOMING_WEBHOOK="${{ inputs.jira_webhook_url }}"
 
-        # Rebuild NEW_STABLE_TAGS as an array
-        for i in ${NEW_STABLE_TAGS[@]}; do
-          NEW_RELEASE_TAGS+=("$i")
-        done
+    #     # Rebuild NEW_STABLE_TAGS as an array
+    #     for i in ${NEW_STABLE_TAGS[@]}; do
+    #       NEW_RELEASE_TAGS+=("$i")
+    #     done
 
-        # Create new JIRA versions (old way of doing it)
-        # TODO: add a future capacity to determine whether the release is hotfix or standard (using TYPE)
-        # OR: rely on jira automation to do it (less hassle on github side, and jira knows jira best)
+    #     # Create new JIRA versions (old way of doing it)
+    #     # TODO: add a future capacity to determine whether the release is hotfix or standard (using TYPE)
+    #     # OR: rely on jira automation to do it (less hassle on github side, and jira knows jira best)
 
-        # Build JSON vars for JIRA_RELEASE_DATA
-        JIRA_RELEASE_ARCHIVED="false"
-        JIRA_RELEASE_DESCRIPTION=""
-        JIRA_RELEASE_DATE="$(date +%Y-%m-%d)"
-        JIRA_RELEASE_NAME=""
-        JIRA_PROJECT_ID="${{ inputs.jira_project_id }}"
-        JIRA_RELEASE_RELEASED="false"
-        JIRA_RELEASE_ID="$(git log |grep -E "Centreon\ next.*\#[0-9]{5,}\#\)" |grep -o -P "(?<=#)[0-9]{5,}(?=#)" |head -n 1)"
+    #     # Build JSON vars for JIRA_RELEASE_DATA
+    #     JIRA_RELEASE_ARCHIVED="false"
+    #     JIRA_RELEASE_DESCRIPTION=""
+    #     JIRA_RELEASE_DATE="$(date +%Y-%m-%d)"
+    #     JIRA_RELEASE_NAME=""
+    #     JIRA_PROJECT_ID="${{ inputs.jira_project_id }}"
+    #     JIRA_RELEASE_RELEASED="false"
+    #     JIRA_RELEASE_ID="$(git log |grep -E "Centreon\ next.*\#[0-9]{5,}\#\)" |grep -o -P "(?<=#)[0-9]{5,}(?=#)" |head -n 1)"
 
-        # Create JIRA version for each released component
-        echo "Creating JIRA releases."
-        for TAG in ${NEW_RELEASE_TAGS[@]}; do
-          if [ -n $TAG ]; then
-            echo "::notice::Creating JIRA release $TAG based on git release tag $TAG."
-            # Build JSON with release information for JIRA API
-            JIRA_RELEASE_DATA=$(jq -nc \
-              --arg archived "$JIRA_RELEASE_ARCHIVED" \
-              --arg description "$JIRA_RELEASE_ID $TAG" \
-              --arg releaseDate "$JIRA_RELEASE_DATE" \
-              --arg name "$TAG" \
-              --arg projectId "$JIRA_PROJECT_ID" \
-              --arg released "$JIRA_RELEASE_RELEASED" \
-              '$ARGS.named' )
-            # Send to JIRA API release
-            echo "Sending to JIRA API release: $JIRA_RELEASE_DATA"
-            curl --fail --request POST \
-              --url "${{ inputs.jira_base_url }}/rest/api/3/version" \
-              --user '${{ inputs.jira_user_email }}:${{ inputs.jira_api_token }}' \
-              --header 'Accept: application/json' \
-              --header 'Content-Type: application/json' \
-              --data "$JIRA_RELEASE_DATA"
-          else
-            echo "::error::Release tag $TAG was empty, exiting."
-            exit 1
-          fi
-        done
-      shell: bash
+    #     # Create JIRA version for each released component
+    #     echo "Creating JIRA releases."
+    #     for TAG in ${NEW_RELEASE_TAGS[@]}; do
+    #       if [ -n $TAG ]; then
+    #         echo "::notice::Creating JIRA release $TAG based on git release tag $TAG."
+    #         # Build JSON with release information for JIRA API
+    #         JIRA_RELEASE_DATA=$(jq -nc \
+    #           --arg archived "$JIRA_RELEASE_ARCHIVED" \
+    #           --arg description "$JIRA_RELEASE_ID $TAG" \
+    #           --arg releaseDate "$JIRA_RELEASE_DATE" \
+    #           --arg name "$TAG" \
+    #           --arg projectId "$JIRA_PROJECT_ID" \
+    #           --arg released "$JIRA_RELEASE_RELEASED" \
+    #           '$ARGS.named' )
+    #         # Send to JIRA API release
+    #         echo "Sending to JIRA API release: $JIRA_RELEASE_DATA"
+    #         curl --fail --request POST \
+    #           --url "${{ inputs.jira_base_url }}/rest/api/3/version" \
+    #           --user '${{ inputs.jira_user_email }}:${{ inputs.jira_api_token }}' \
+    #           --header 'Accept: application/json' \
+    #           --header 'Content-Type: application/json' \
+    #           --data "$JIRA_RELEASE_DATA"
+    #       else
+    #         echo "::error::Release tag $TAG was empty, exiting."
+    #         exit 1
+    #       fi
+    #     done
+    #   shell: bash
 
-    - name: Trigger release communication for new releases
-      run: |
-        set -eux
+    # - name: Trigger release communication for new releases
+    #   run: |
+    #     set -eux
 
-        MAJOR_VERSION=$CURRENT_STABLE_BRANCH_MAJOR_VERSION
+    #     MAJOR_VERSION=$CURRENT_STABLE_BRANCH_MAJOR_VERSION
 
-        # Webhook url
-        JIRA_INCOMING_WEBHOOK="${{ inputs.jira_webhook_url }}"
+    #     # Webhook url
+    #     JIRA_INCOMING_WEBHOOK="${{ inputs.jira_webhook_url }}"
 
-        # Rebuild NEW_STABLE_TAGS as an array (required to build a proper json)
-        for i in ${NEW_STABLE_TAGS[@]}; do
-          if [ -n "$i" ]; then
-            NEW_RELEASE_TAGS+=("$i")
-          else
-            echo "::error::Release tag $i was empty, exiting."
-            exit 1
-          fi
-        done
+    #     # Rebuild NEW_STABLE_TAGS as an array (required to build a proper json)
+    #     for i in ${NEW_STABLE_TAGS[@]}; do
+    #       if [ -n "$i" ]; then
+    #         NEW_RELEASE_TAGS+=("$i")
+    #       else
+    #         echo "::error::Release tag $i was empty, exiting."
+    #         exit 1
+    #       fi
+    #     done
 
-        # Build JSON structure with released versions
-        JSON_TAGS=$(jq -n '{componentList:$ARGS.positional}' --args "${NEW_RELEASE_TAGS[@]}")
-        JSON_VERSION_INFO=$(jq -n --arg majorVersion "$MAJOR_VERSION" --arg scopeVersion "$SCOPE_VERSION" '$ARGS.named' )
-        RELEASE_JSON=$(echo "$JSON_VERSION_INFO" | jq -c --argjson json_tags "$JSON_TAGS" '. += $json_tags')
+    #     # Build JSON structure with released versions
+    #     JSON_TAGS=$(jq -n '{componentList:$ARGS.positional}' --args "${NEW_RELEASE_TAGS[@]}")
+    #     JSON_VERSION_INFO=$(jq -n --arg majorVersion "$MAJOR_VERSION" --arg scopeVersion "$SCOPE_VERSION" '$ARGS.named' )
+    #     RELEASE_JSON=$(echo "$JSON_VERSION_INFO" | jq -c --argjson json_tags "$JSON_TAGS" '. += $json_tags')
 
-        # DEBUG
-        echo "JSON_TAGS: \r\n$JSON_TAGS"
-        echo "JSON_VERSION_INFO: $JSON_VERSION_INFO"
-        echo "Sending to JIRA automation: \r\n$RELEASE_JSON"
+    #     # DEBUG
+    #     echo "JSON_TAGS: \r\n$JSON_TAGS"
+    #     echo "JSON_VERSION_INFO: $JSON_VERSION_INFO"
+    #     echo "Sending to JIRA automation: \r\n$RELEASE_JSON"
 
-        # Call jira webhook to trigger the communication workflow
-        # and provide versions data for communication
-        curl \
-          "$JIRA_INCOMING_WEBHOOK" \
-          -X POST \
-          -H 'Content-type: application/json' \
-          --data "$RELEASE_JSON"
+    #     # Call jira webhook to trigger the communication workflow
+    #     # and provide versions data for communication
+    #     curl \
+    #       "$JIRA_INCOMING_WEBHOOK" \
+    #       -X POST \
+    #       -H 'Content-type: application/json' \
+    #       --data "$RELEASE_JSON"
 
-      shell: bash
+    #   shell: bash
